### ISSUE TITLE
Running time exception: Could not find a starting point in the set

### ISSUE THREAD

**Issue by simmonssong** [figlerg/anyHR#1]
Hi, thanks for your code.
I get `Exception('Could not find a starting point in the set')` when I am generating samples with 10 variables. The constraint is `x0+x1+x2+x3+x4+x5+x6+x7+x8+x9<1` with the bound `[0, 1]` for all 10 variables. It seems that `[-1, 1]` or `[-1, 0]` are okay but not for `[0, 1]` in this case. However, with the bound `[0, 1]`, `x0+x1+x2+x3+x4+x5+x6<1` successes.

The entire error code:
> Traceback (most recent call last):
  File ".../anyHR/examples/test2.py", line 220, in <module>
    rejections, elapsed, samples = sample_n_cube_hr(dim=10)
  File ".../anyHR/examples/test2.py", line 190, in sample_n_cube_hr
    hr = HitAndRun(constraint=c, bounding_box=bounds)
  File ".../anyHR/anyHR/hit_and_run/hit_and_run.py", line 53, in __init__
    self.starting_point = self._starting_point_pso()
  File ".../anyHR/anyHR/hit_and_run/hit_and_run.py", line 344, in _starting_point_pso
    raise Exception('Could not find a starting point in the set.')
Exception: Could not find a starting point in the set.

Here are some informations of my environment:
> Ubuntu 18.04.6 LTS
Python 3.9.7
z3 0.2.0
z3-solver 4.8.15.0
antlr4-python3-runtime 4.9.3

I follow the function `anyHR/examples/test.py sample_n_sphere_hr` to finish my practice. This exception also arises in `sample_n_sphere_hr` when I set `dim=20`.

**Comment by figlerg** [comment]
Hi, thanks for reaching out. This issue slipped my attention, sorry for the late reply.

This is a problem that has been coming up a lot for PSO: Since this algorithm is merely an optimizer that searches the space for an initial satisfying sample, it is not guaranteed to terminate within the budget of iterations it has.

Thus, I cannot really solve this problem completely- but maybe I can improve the UI sufficiently to make it more manageable. 

Until I do that, I advise you to either 
1. think about whether it is possible for your application to use only linear constraints and switch to the InitPoint.SMT option or
2. look at the internal parameters inside the pso.py file and see if changing them achieves better results.

Hope this helps somehow!

Best,
Felix
